<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net8.0</TargetFramework>
    <RootNamespace>Alina.Bridge.Tests</RootNamespace>
    <AssemblyName>Alina.Bridge.Tests</AssemblyName>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="..\Alina.Bridge\Alina.Bridge.csproj" />
  </ItemGroup>
</Project>

